# Generated by Django 4.1.1 on 2022-10-02 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipeingridient",
            old_name="quantity",
            new_name="amount",
        ),
    ]
