# Generated by Django 4.1.1 on 2022-10-08 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_quantity_recipeingridient_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingridient",
            name="amount",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=0.1,
                        message="Количество не может быть меньше 0",
                    )
                ],
                verbose_name="Количество",
            ),
        ),
    ]
